version: "3.3"

services:
  php:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: botanica
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

